const express = require('express');
const router = express.Router();
const ctrl = require('../../controllers/admin/usersController');
router.get('/students', ctrl.listStudents);
router.post('/students', ctrl.createStudent);
router.put('/students/:id', ctrl.updateStudent);
router.put('/students/:id/disable', ctrl.disableStudent);
router.get('/teachers', ctrl.listTeachers);
router.post('/teachers', ctrl.createTeacher);
router.put('/teachers/:id', ctrl.updateTeacher);
router.put('/teachers/:id/disable', ctrl.disableTeacher);
router.post('/reset-password', ctrl.resetPassword);
router.post('/profile-photo/approve', ctrl.approvePhoto);
module.exports = router;
